services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:mysql://db:3306/talentflowhr_db
      - DB_USER=talentflow_theber
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: talentflowhr_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: